name: veil
description: Veil Messenger - Говори свободно.
publish_to: 'none'
version: 2.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  google_fonts: ^6.1.0
  
  # Хранилище
  flutter_secure_storage: ^9.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Состояние и навигация
  flutter_riverpod: ^2.5.0
  go_router: ^14.0.0
  
  # QR
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1
  
  # Криптография
  pointycastle: ^3.7.4
  bip39_mnemonic: ^3.0.0
  otp: ^3.1.4
  argon2: ^1.0.1
  x25519: ^0.1.0
  ed25519_edwards: ^0.3.0
  
  # HTTP и WebSocket
  dio: ^5.4.0
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  
  # Файлы и медиа
  file_picker: ^6.2.0
  image_picker: ^1.0.7
  share_plus: ^7.2.1
  url_launcher: ^6.2.5
  
  # Другое
  emoji_picker_flutter: ^1.6.4
  uuid: ^4.3.3

  # WebRTC
  flutter_webrtc: ^0.9.0
  sdp_transform: ^0.3.2

  # Звук
  audioplayers: ^6.4.0
  path_provider: ^2.1.0

  # Firebase
  firebase_core: ^2.32.0      # <-- ДОБАВЛЕНО
  firebase_messaging: ^14.9.4 # <-- ДОБАВЛЕНО
  flutter_local_notifications: ^17.0.0  # <-- ДОБАВЛЕНО
  record: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_test: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/