name: veil
description: Veil Messenger - Говори свободно.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: ^6.1.0
  flutter_secure_storage: ^9.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.5.0
  go_router: ^14.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1
  pointycastle: ^3.7.4
  bip39_mnemonic: ^3.0.0
  otp: ^3.2.0
  argon2: ^1.0.1
  dio: ^5.4.0
  bip39: ^1.0.6
  emoji_picker_flutter: ^4.4.0
  image_picker: ^1.1.2
  cryptography: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true