// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGL4B3VxjWGuRM3XINycMNs4Jdpb8BV3I',
    appId: '1:459563944680:web:e7900a2e84f7324dcf975d',
    messagingSenderId: '459563944680',
    projectId: 'veil-messenger-aea31',
    authDomain: 'veil-messenger-aea31.firebaseapp.com',
    storageBucket: 'veil-messenger-aea31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUVRPfElp2gtQbs78lB-NlvGjUkTlQ4Dw',
    appId: '1:459563944680:android:251ff7b4779855fdcf975d',
    messagingSenderId: '459563944680',
    projectId: 'veil-messenger-aea31',
    storageBucket: 'veil-messenger-aea31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjuQFN-2-3zjRhc8mrZ-HjQgYThQQ9-II',
    appId: '1:459563944680:ios:c95be135633068e7cf975d',
    messagingSenderId: '459563944680',
    projectId: 'veil-messenger-aea31',
    storageBucket: 'veil-messenger-aea31.firebasestorage.app',
    iosBundleId: 'com.veil.veil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGL4B3VxjWGuRM3XINycMNs4Jdpb8BV3I',
    appId: '1:459563944680:web:caa3f0ca152b59b5cf975d',
    messagingSenderId: '459563944680',
    projectId: 'veil-messenger-aea31',
    authDomain: 'veil-messenger-aea31.firebaseapp.com',
    storageBucket: 'veil-messenger-aea31.firebasestorage.app',
  );
}